import { readFileSync } from 'node:fs';
import { defineConfig, envField } from 'astro/config';

// Single source of truth for the domain: public/CNAME
const domain = readFileSync(new URL('./public/CNAME', import.meta.url), 'utf8').trim().toLowerCase();

export default defineConfig({
  site: `https://${domain}`,
  trailingSlash: 'ignore',
  // Imprint contact data is injected at build time (local .env / GitHub repository secrets),
  // so it is published on the site but not stored in the public repository.
  env: {
    schema: {
      CONTACT_STREET: envField.string({ context: 'server', access: 'public' }),
      CONTACT_CITY: envField.string({ context: 'server', access: 'public' }),
      CONTACT_PHONE: envField.string({ context: 'server', access: 'public' }),
      CONTACT_PHONE_E164: envField.string({ context: 'server', access: 'public' }),
      CONTACT_EMAIL: envField.string({ context: 'server', access: 'public' }),
      CONTACT_VAT_ID: envField.string({ context: 'server', access: 'public' }),
    },
  },
  build: {
    inlineStylesheets: 'always',
  },
  // Content Security Policy as <meta>: GitHub Pages cannot set response headers.
  // Script and style hashes are generated by Astro; everything else is same-origin only.
  security: {
    csp: {
      directives: [
        "default-src 'self'",
        "img-src 'self' data:",
        "font-src 'self'",
        "connect-src 'self'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'none'",
      ],
    },
  },
  markdown: {
    // Prism uses CSS classes instead of inline styles, which keeps the CSP strict
    syntaxHighlight: 'prism',
    // Blog articles are German: typographic German quotes
    smartypants: {
      openingQuotes: { double: '„', single: '‚' },
      closingQuotes: { double: '“', single: '‘' },
    },
  },
  vite: {
    server: {
      watch: { usePolling: process.env.ASTRO_POLLING === 'true', interval: 300 },
    },
  },
});
