import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';

// Single source of truth for the domain: public/CNAME
const domain = readFileSync(new URL('./public/CNAME', import.meta.url), 'utf8').trim().toLowerCase();

export default defineConfig({
  site: `https://${domain}`,
  trailingSlash: 'ignore',
  build: {
    inlineStylesheets: 'always',
  },
  // Content Security Policy as <meta>: GitHub Pages cannot set response headers.
  // Script and style hashes are generated by Astro; everything else is same-origin only.
  security: {
    csp: {
      directives: [
        "default-src 'self'",
        "img-src 'self' data:",
        "font-src 'self'",
        "connect-src 'self'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'none'",
      ],
    },
  },
  markdown: {
    syntaxHighlight: false,
  },
  vite: {
    server: {
      watch: { usePolling: process.env.ASTRO_POLLING === 'true', interval: 300 },
    },
  },
});
